name: CI Builds

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-16.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Set OS
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
          sudo apt-get install libncurses5-dbg
      - uses: actions/checkout@v2
      - name: Install {fmt}
        run: |
          git clone https://github.com/fmtlib/fmt.git
          mkdir fmt/build && cd fmt/build
          cmake ..
          make
          make install
      - name: Compile
        run: g++ main.cc 
      - name: Run
        run: ./a.out
    
  win64:
    name: Windows 64-bit
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make git dos2unix
      - name: Install {fmt}
        run: |
          git clone https://github.com/fmtlib/fmt.git
          mkdir fmt/build && cd fmt/build
          cmake ..
          make
          make install
      - name: Compile
        run: g++ main.cc 
      - name: Run
        run: ./a.out
