name: CI Builds

on: [push]

env:
  FMT_VERSION: '7.1.3'

jobs:

  linux:
    name: Linux
    env:
      HOST_TRIPLE: 'x86_64-unknown-linux-gnu'
      INSTALL_PREFIX: '/opt/smelibs'
      SUDOCMD: 'sudo'
    runs-on: ubuntu-16.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Set OS
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
          sudo apt-get install libncurses5-dbg
      - uses: actions/checkout@v2
      - name: Install {fmt}
        run: ./install-fmt
      - name: Compile
        run: g++ -I/opt/smelibs/include -L/opt/smelibs/lib -lfmt -std=c++17 main.cc
      - name: Run
        run: ./a.out

  win64:
    name: Windows 64-bit
    runs-on: windows-2019
    env:
      HOST_TRIPLE: 'x86_64-w64-mingw64'
      INSTALL_PREFIX: '/c/smelibs'
      SUDOCMD: ''
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make git dos2unix
      - name: Install {fmt}
        run: ./install-fmt
      - name: Compile
        run: g++ -I/c/smelibs/include -L/c/smelibs/lib -lfmt -std=c++17 main.cc
      - name: Run
        run: ./a.out
